DROP TABLE IF EXISTS plants;

CREATE TABLE plants (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	type TEXT NOT NULL,
	lastWatered DATE NOT NULL,
	dryOut INTEGER NOT NULL,
	remaining TINYINT,
	timeEllapsed INTEGER);

CREATE TABLE pod(
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	filePath TEXT NOT NULL);

CREATE TABLE garden (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	lastWatered DATE NOT NULL,
	dryOut INTEGER NOT NULL,
	remaining TINYINT);
